# Site settings
title: Introduction au développement web
description: >
  Introduction to web development.
baseurl: "/web"
url: "http://maelquerre.github.io"
github_username: glascode
# Build settings
include: ['_pages']
kramdown:
  input: GFM
