# Site settings
title: Introduction au développement web
email: glascode.x@gmail.com
description: >
  Introduction to web development.
baseurl: ""
url: "http://localhost:4000"
github_username: glascode
# Build settings
include: ['_pages']
kramdown:
  input: GFM
