# Site settings
title: Introduction web
email: glascode.x@gmail.com
description: >
  Introduction to web development.
baseurl: "/introduction-web"
url: "http://glascode.github.io"
github_username: glascode
# Build settings
include: ['_pages']
kramdown:
  input: GFM
